### ISSUE TITLE
Question: What's the purpose of this line of code?

### ISSUE THREAD

**Issue by oblitum** [mgutz/logxi#8]
I'm trying to make sense of this line of code but I dunno what it does. It seems the preceding code does enough for the current intent.

https://github.com/mgutz/logxi/blob/master/v1/env.go#L107

**Comment by mgutz** [comment]
disables a named logger. For example, this enables all loggers and disables logger named `foo`

`LOGXI=*,-foo`

**Comment by oblitum** [comment]
Indeed, I've checked what it does, that part of the code. What I don't get is what that line specifically is doing. Is it necessary or purposeful?

**Comment by oblitum** [comment]
You update the map, but also the `key` of the loop that doesn't seem useful since you're going to `continue` the loop.

**Comment by mgutz** [comment]
Oh that line. It falls through resetting the deleted logger level to its default value, which is ERR in production. `logxi` always tries to show errors.

**Comment by oblitum** [comment]
OK, thanks!

**Comment by oblitum** [comment]
I guess I need to study some more Go, my mind is looping to make sense of that to no avail =/.

1- `key` is a loop variable
2- you set it and `continue`
3- the setting seems to produce no effect since at the new loop iteration, the next element of the map will be use to make a brand "new" `key` loop variable.

**Comment by mgutz** [comment]
I think you're on to something. The delete should not be there and it's a no-no to add/remove elements from a map in a loop. Must be leftover from a refactor (at least that's my story).

Loop variables for map ranges are by value. Removing the prefix '-' is harmless. 

You found a subtle bug. I should be handling user typos. The map should be checked to ensure the key exists before setting the level otherwise I am introducing a new key changing the map itself. I consider it a bug and thanks again for reviewing it.

**Comment by oblitum** [comment]
Ah ok  thanks, at last I can feel better for not feeling crazy =D

**Comment by oblitum** [comment]
@mgutz even if removing the prefix is harmless does does the assignment in `key = key[1:]; continue;` have any use? I don't see it.
